###get-all-products
GET http://localhost:8091/product/all
accept: application/json

###create-product
POST http://localhost:8091/product
accept: application/json
Content-Type: application/json

{
	"description": "slr-camera",
    "price": 750
}

###
POST http://localhost:8091/product
accept: application/json
Content-Type: application/json

{
  "description": "headphone",
  "price": 100
}

###get-product-by-id
GET http://localhost:8091/product/629ea0c0e101bd0205fce78c

###get-product-by-price-range
GET http://localhost:8091/product/price-range?min=750&max=800

###update-product
### 왜인지 모르겠지만 PUT이 안먹힌다
PUT http://localhost:8091/product/629ea0c0e101bd0205fce78c
accept: application/json
Content-Type: application/json

{
	"description": "slr-camera",
	"price": 800
}

###delete-product
DELETE http://localhost:8091/product/629dd104540f273be6fc50e6