###get-all-products
GET http://localhost:8080/product/all
accept: application/json

###create-product
POST http://localhost:8080/product
accept: application/json
Content-Type: application/json

{
	"description": "slr-camera",
	"price": 750
}

###get-product-by-id
GET http://localhost:8080/product/629dd104540f273be6fc50e6

###update-product
### 왜인지 모르겠지만 PUT이 안먹힌다
PUT http://localhost:8080/product/629dd104540f273be6fc50e6
accept: application/json
Content-Type: application/json

{
	"description": "slr-camera",
	"price": 800
}

###delete-product
DELETE http://localhost:8080/product/629dd104540f273be6fc50e6